# Generated by Django 6.0.1 on 2026-01-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
