# Generated by Django 6.0.1 on 2026-01-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment_actual_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_available',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
