# Generated by Django 6.0.1 on 2026-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_department_location_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
